[colors]
accent = '#8B5CF6FF'
background = '#0A0A0AFF'
base00 = '#0A0A0AFF'
base01 = '#DC2626FF'
base02 = '#16A34AFF'
base03 = '#CA8A04FF'
base04 = '#2563EBFF'
base05 = '#9333EAFF'
base06 = '#0891B2FF'
base07 = '#FAFAFAFF'
base08 = '#1C1C1CFF'
base09 = '#EF4444FF'
base0A = '#EAB308FF'
base0B = '#84CC16FF'
base0C = '#06B6D4FF'
base0D = '#3B82F6FF'
base0E = '#A855F7FF'
base0F = '#737373FF'
border = '#1C1C1CFF'
border_focused = '#404040FF'
cursor = '#8B5CF6FF'
editor_background = '#0A0A0AFF'
editor_command = '#8B5CF6FF'
editor_comment = '#525252FF'
editor_disabled = '#404040FF'
editor_emphasis = '#A78BFAFF'
editor_error = '#DC2626FF'
editor_inactive = '#404040FF'
editor_line_number = '#525252FF'
editor_link = '#60A5FAFF'
editor_main = '#FAFAFAFF'
editor_selected = '#1C1C1CFF'
editor_selection_inactive = '#141414FF'
editor_string = '#4ADE80FF'
editor_success = '#22C55EFF'
editor_warning = '#F59E0BFF'
error = '#DC2626FF'
foreground = '#FAFAFAFF'
info = '#60A5FAFF'
on_background = '#FAFAFAFF'
on_error = '#FAFAFAFF'
on_info = '#0A0A0AFF'
on_success = '#0A0A0AFF'
on_surface = '#E5E5E5FF'
on_surface_variant = '#A3A3A3FF'
on_warning = '#0A0A0AFF'
success = '#22C55EFF'
surface = '#111111FF'
surface_variant = '#141414FF'
warning = '#F59E0BFF'

[general]
name = 'dark'